{
  "formatVersion": "1.1",
  "component": {
    "group": "magik",
    "module": "single",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "single-1.0.jar",
          "url": "single-1.0.jar",
          "size": 1471,
          "sha512": "723a3dfb47ce9f4c6cad3b1d928610281fd78c586772878c88a0ed81a57158bc2ffdea7b714a8a63b1fae177612b39906e6e9874d10e4797e775808815be1596",
          "sha256": "5b5572737a58834be78c60cdfe928c986110022f6bc68e88f43cfd7bb7af71b4",
          "sha1": "875a3a426d67f6e9e49d1db10e324221a71ad4ff",
          "md5": "4fe751dab3afd1bb6b0769fa4d206032"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "single-1.0.jar",
          "url": "single-1.0.jar",
          "size": 1471,
          "sha512": "723a3dfb47ce9f4c6cad3b1d928610281fd78c586772878c88a0ed81a57158bc2ffdea7b714a8a63b1fae177612b39906e6e9874d10e4797e775808815be1596",
          "sha256": "5b5572737a58834be78c60cdfe928c986110022f6bc68e88f43cfd7bb7af71b4",
          "sha1": "875a3a426d67f6e9e49d1db10e324221a71ad4ff",
          "md5": "4fe751dab3afd1bb6b0769fa4d206032"
        }
      ]
    }
  ]
}
