{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.sample",
    "module": "prova",
    "version": "0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "prova-0.1.jar",
          "url": "prova-0.1.jar",
          "size": 1471,
          "sha512": "3758d563a881c99c0d38a8c0a796d4e861c33a157607d07d242cf22ffd0a3cd6dd66a0bf59d74ae434a41bd2de74afca41a483a5a799d7509167f5b1b1b8d372",
          "sha256": "0fc40010e54a48547a3e0a2870d2ad8aa7efe3ad3725b00e5c08686a4c855345",
          "sha1": "957df9938b6f1c1c168277933dadc42503df9874",
          "md5": "6d76ae3b0efc6eaf628122396b9417cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "prova-0.1.jar",
          "url": "prova-0.1.jar",
          "size": 1471,
          "sha512": "3758d563a881c99c0d38a8c0a796d4e861c33a157607d07d242cf22ffd0a3cd6dd66a0bf59d74ae434a41bd2de74afca41a483a5a799d7509167f5b1b1b8d372",
          "sha256": "0fc40010e54a48547a3e0a2870d2ad8aa7efe3ad3725b00e5c08686a4c855345",
          "sha1": "957df9938b6f1c1c168277933dadc42503df9874",
          "md5": "6d76ae3b0efc6eaf628122396b9417cf"
        }
      ]
    }
  ]
}
