{
  "formatVersion": "1.1",
  "component": {
    "group": "org.gradle.sample",
    "module": "prova",
    "version": "0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "prova-0.2.jar",
          "url": "prova-0.2.jar",
          "size": 1471,
          "sha512": "d20727ee435dc12fbf6a9b313d1e4c1c812180880497be1ab08d357de124fab4013577a91efd900fca1f85e964ca117c4869eb5c69be11ab6523cc849902a913",
          "sha256": "485f9c3e3d5f1884fb05b3d211aec7022d566c5bfb0f3d9bf291e82c5bb6428d",
          "sha1": "e20b1dfa229c1c188b50ea340e965b5da77bd557",
          "md5": "cea1eb4f085531238aef2294fe663954"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "prova-0.2.jar",
          "url": "prova-0.2.jar",
          "size": 1471,
          "sha512": "d20727ee435dc12fbf6a9b313d1e4c1c812180880497be1ab08d357de124fab4013577a91efd900fca1f85e964ca117c4869eb5c69be11ab6523cc849902a913",
          "sha256": "485f9c3e3d5f1884fb05b3d211aec7022d566c5bfb0f3d9bf291e82c5bb6428d",
          "sha1": "e20b1dfa229c1c188b50ea340e965b5da77bd557",
          "md5": "cea1eb4f085531238aef2294fe663954"
        }
      ]
    }
  ]
}
